-- File is no longer in use!
local mkdirIfNotExist = function (path)
    local _result, _error, _name = vim.uv.fs_mkdir(path, tonumber("755", 8))
    if (_result ~= nil) then
        print("Created directory", path)
    elseif (_name == "EEXIST") then
        print("Directory", path, "already exists!")
    else
        print("Could not create directory ", path, " ", _error)
    end
end

local writeFileContent = function (path, content)
     local _fd, _error = vim.uv.fs_open(path, "w", 438)
     if not _fd then
         print("Could not write file", path, ":", _error)
         return
     end
     vim.uv.fs_write(_fd, content, 0)
     vim.uv.fs_close(_fd)
end

 vim.api.nvim_create_user_command("OpenDirCmcp", function()
     local _DIRECTORY_PATH = "/home/nikhil/workspace/learning/cmcp/"
     mkdirIfNotExist(_DIRECTORY_PATH)
     vim.cmd({
         cmd = "edit",
         args = { _DIRECTORY_PATH },
         magic = { file = false, bar = false },
     })
 end, {
 })

 vim.api.nvim_create_user_command("ResetCmcp", function()
     local _DIRECTORY_PATH = "/home/nikhil/workspace/learning/cmcp/"
     writeFileContent(_DIRECTORY_PATH .. "code.cpp", [[
// File is auto generated by lua script located at ~/.config/nvim/lua/plugins/cmcp.lua
// Happy fucking coding!
#include <bits/stdc++.h>

int main(void) {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(nullptr);
    std::cout << std::flush;
    return 0;
}]])
     writeFileContent(_DIRECTORY_PATH .. "input", [[]])
     writeFileContent(_DIRECTORY_PATH .. "output", [[]])
     writeFileContent(_DIRECTORY_PATH .. "expected", [[]])

     writeFileContent(_DIRECTORY_PATH .. "Makefile", [[
.PHONY: build test
build:
	clang++ -o ./a.out code.cpp -Wall -Wextra -Wpedantic

test: build
	./a.out < input > output
	diff output expected
     ]])
 end, {
 })
